### ISSUE TITLE
Little error in the installing instructions

### ISSUE THREAD

**Issue by agirones** [xdebbie/forkkit#10]
Hi   @xdebbie! I had just cloned the repository to try to help in this project. And I had noticed that there is a little error in one of the installation commands of the README.md. 
![Screenshot from 2020-10-06 15-35-11](https://user-images.githubusercontent.com/55933050/95208612-a1e75980-07e9-11eb-9731-d3c5f0cf9eb0.png)
It would be nice if you could label the issue as hackoberfest and assign it to me.
I hope it helps!

**Comment by xdebbie** [comment]
Hi @agirones , thank you for the input! Sure, it is labelled and assigned now. Thank you!

**Comment by dhruvdesmond** [comment]
u are in the wrong directory. this is not even a bug.

**Comment by xdebbie** [comment]
Hey @dhruvdesmond, have you managed to run the script on your computer following the instructions?

**Comment by dhruvdesmond** [comment]
yes. just cd forkkit and run the command
